import { ComponentName, DesignSystem } from './types/design-systems';

export const componentNameMap: Record<
  ComponentName,
  Record<DesignSystem, string>
> = {
  Button: {
    shadcn: 'Button',
    mui: 'Button',
    antd: 'Button',
    chakra: 'Button',
    primer: 'Button',
    polaris: 'Button',
    carbon: 'Button',
    fluent: 'Button',
    lightning: 'Button',
    atlaskit: 'Button',
  },
  Input: {
    shadcn: 'Input',
    mui: 'TextField',
    antd: 'Input',
    chakra: 'Input',
    primer: 'TextInput',
    polaris: 'TextField',
    carbon: 'TextInput',
    fluent: 'Input',
    lightning: 'Input',
    atlaskit: 'Textfield',
  },
  Card: {
    shadcn: 'Card',
    mui: 'Card',
    antd: 'Card',
    chakra: 'Card',
    primer: 'Card',
    polaris: 'Card',
    carbon: 'Tile',
    fluent: 'Card',
    lightning: 'Card',
    atlaskit: 'Card',
  },
  Select: {
    shadcn: 'Select',
    mui: 'Select',
    antd: 'Select',
    chakra: 'Select',
    primer: 'Select',
    polaris: 'Select',
    carbon: 'Select',
    fluent: 'Dropdown',
    lightning: 'Combobox',
    atlaskit: 'Select',
  },
  Checkbox: {
    shadcn: 'Checkbox',
    mui: 'Checkbox',
    antd: 'Checkbox',
    chakra: 'Checkbox',
    primer: 'Checkbox',
    polaris: 'Checkbox',
    carbon: 'Checkbox',
    fluent: 'Checkbox',
    lightning: 'Checkbox',
    atlaskit: 'Checkbox',
  },
  Radio: {
    shadcn: 'RadioGroup',
    mui: 'Radio',
    antd: 'Radio',
    chakra: 'Radio',
    primer: 'Radio',
    polaris: 'RadioButton',
    carbon: 'RadioButton',
    fluent: 'Radio',
    lightning: 'RadioGroup',
    atlaskit: 'Radio',
  },
  Switch: {
    shadcn: 'Switch',
    mui: 'Switch',
    antd: 'Switch',
    chakra: 'Switch',
    primer: 'Switch',
    polaris: 'Switch',
    carbon: 'Toggle',
    fluent: 'Switch',
    lightning: 'Switch',
    atlaskit: 'Toggle',
  },
  Textarea: {
    shadcn: 'Textarea',
    mui: 'TextField',
    antd: 'TextArea',
    chakra: 'Textarea',
    primer: 'Textarea',
    polaris: 'TextField',
    carbon: 'TextArea',
    fluent: 'Textarea',
    lightning: 'Textarea',
    atlaskit: 'Textarea',
  },
  Badge: {
    shadcn: 'Badge',
    mui: 'Chip',
    antd: 'Badge',
    chakra: 'Badge',
    primer: 'Label',
    polaris: 'Badge',
    carbon: 'Tag',
    fluent: 'Badge',
    lightning: 'Badge',
    atlaskit: 'Badge',
  },

  Tooltip: {
    shadcn: 'Tooltip',
    mui: 'Tooltip',
    antd: 'Tooltip',
    chakra: 'Tooltip',
    primer: 'Tooltip',
    polaris: 'Tooltip',
    carbon: 'Tooltip',
    fluent: 'Tooltip',
    lightning: 'Tooltip',
    atlaskit: 'Tooltip',
  },
  Progress: {
    shadcn: 'Progress',
    mui: 'LinearProgress',
    antd: 'Progress',
    chakra: 'Progress',
    primer: 'ProgressBar',
    polaris: 'ProgressBar',
    carbon: 'ProgressBar',
    fluent: 'ProgressBar',
    lightning: 'ProgressBar',
    atlaskit: 'ProgressBar',
  },
  Skeleton: {
    shadcn: 'Skeleton',
    mui: 'Skeleton',
    antd: 'Skeleton',
    chakra: 'Skeleton',
    primer: 'Skeleton',
    polaris: 'SkeletonBodyText',
    carbon: 'SkeletonText',
    fluent: 'Skeleton',
    lightning: 'Skeleton',
    atlaskit: 'Skeleton',
  },
  Alert: {
    shadcn: 'Alert',
    mui: 'Alert',
    antd: 'Alert',
    chakra: 'Alert',
    primer: 'Flash',
    polaris: 'Banner',
    carbon: 'InlineNotification',
    fluent: 'MessageBar',
    lightning: 'Alert',
    atlaskit: 'SectionMessage',
  },
  Dialog: {
    shadcn: 'Dialog',
    mui: 'Dialog',
    antd: 'Modal',
    chakra: 'Modal',
    primer: 'Dialog',
    polaris: 'Modal',
    carbon: 'Modal',
    fluent: 'Dialog',
    lightning: 'Modal',
    atlaskit: 'ModalDialog',
  },
  Toast: {
    shadcn: 'Toast',
    mui: 'Snackbar',
    antd: 'message',
    chakra: 'Toast',
    primer: 'Toast',
    polaris: 'Toast',
    carbon: 'ToastNotification',
    fluent: 'Toast',
    lightning: 'Toast',
    atlaskit: 'Flag',
  },
  Tabs: {
    shadcn: 'Tabs',
    mui: 'Tabs',
    antd: 'Tabs',
    chakra: 'Tabs',
    primer: 'TabNav',
    polaris: 'Tabs',
    carbon: 'Tabs',
    fluent: 'TabList',
    lightning: 'Tabs',
    atlaskit: 'Tabs',
  },
  Breadcrumb: {
    shadcn: 'Breadcrumb',
    mui: 'Breadcrumbs',
    antd: 'Breadcrumb',
    chakra: 'Breadcrumb',
    primer: 'Breadcrumbs',
    polaris: 'Breadcrumbs',
    carbon: 'Breadcrumb',
    fluent: 'Breadcrumb',
    lightning: 'Breadcrumb',
    atlaskit: 'Breadcrumbs',
  },
  Menu: {
    shadcn: 'DropdownMenu',
    mui: 'Menu',
    antd: 'Menu',
    chakra: 'Menu',
    primer: 'ActionMenu',
    polaris: 'ActionList',
    carbon: 'Menu',
    fluent: 'Menu',
    lightning: 'Menu',
    atlaskit: 'DropdownMenu',
  },
  Divider: {
    shadcn: 'Separator',
    mui: 'Divider',
    antd: 'Divider',
    chakra: 'Divider',
    primer: 'Divider',
    polaris: 'Divider',
    carbon: 'Divider',
    fluent: 'Divider',
    lightning: 'Divider',
    atlaskit: 'Divider',
  },
  Accordion: {
    shadcn: 'Accordion',
    mui: 'Accordion',
    antd: 'Collapse',
    chakra: 'Accordion',
    primer: 'Accordion',
    polaris: 'Collapsible',
    carbon: 'Accordion',
    fluent: 'Accordion',
    lightning: 'Accordion',
    atlaskit: 'Accordion',
  },
  Drawer: {
    shadcn: 'Sheet',
    mui: 'Drawer',
    antd: 'Drawer',
    chakra: 'Drawer',
    primer: 'Drawer',
    polaris: 'Sheet',
    carbon: 'SideNav',
    fluent: 'Drawer',
    lightning: 'Drawer',
    atlaskit: 'Drawer',
  },
};

export const variantMapping = {
  Button: {
    primary: {
      shadcn: 'default',
      mui: 'contained',
      antd: 'primary',
      chakra: 'solid',
      primer: 'primary',
      polaris: 'primary',
      carbon: 'primary',
      fluent: 'primary',
      lightning: 'brand',
      atlaskit: 'primary',
    },
    secondary: {
      shadcn: 'secondary',
      mui: 'outlined',
      antd: 'default',
      chakra: 'outline',
      primer: 'default',
      polaris: 'secondary',
      carbon: 'secondary',
      fluent: 'secondary',
      lightning: 'neutral',
      atlaskit: 'default',
    },
    outlined: {
      shadcn: 'outline',
      mui: 'outlined',
      antd: 'default',
      chakra: 'outline',
      primer: 'default',
      polaris: 'secondary',
      carbon: 'tertiary',
      fluent: 'outline',
      lightning: 'outline',
      atlaskit: 'subtle',
    },
    text: {
      shadcn: 'ghost',
      mui: 'text',
      antd: 'text',
      chakra: 'ghost',
      primer: 'invisible',
      polaris: 'plain',
      carbon: 'ghost',
      fluent: 'transparent',
      lightning: 'text',
      atlaskit: 'link',
    },
    destructive: {
      shadcn: 'destructive',
      mui: 'error',
      antd: 'danger',
      chakra: 'solid',
      primer: 'danger',
      polaris: 'critical',
      carbon: 'danger',
      fluent: 'danger',
      lightning: 'destructive',
      atlaskit: 'danger',
    },
    ghost: {
      shadcn: 'ghost',
      mui: 'text',
      antd: 'text',
      chakra: 'ghost',
      primer: 'invisible',
      polaris: 'plain',
      carbon: 'ghost',
      fluent: 'transparent',
      lightning: 'text',
      atlaskit: 'subtle',
    },
    link: {
      shadcn: 'link',
      mui: 'text',
      antd: 'link',
      chakra: 'link',
      primer: 'link',
      polaris: 'plain',
      carbon: 'ghost',
      fluent: 'transparent',
      lightning: 'base',
      atlaskit: 'link',
    },
  },
  Badge: {
    default: {
      shadcn: 'default',
      mui: 'default',
      antd: 'default',
      chakra: 'gray',
      primer: 'default',
      polaris: 'info',
      carbon: 'gray',
      fluent: 'filled',
      lightning: 'default',
      atlaskit: 'default',
    },
    primary: {
      shadcn: 'default',
      mui: 'primary',
      antd: 'processing',
      chakra: 'blue',
      primer: 'accent',
      polaris: 'info',
      carbon: 'blue',
      fluent: 'filled',
      lightning: 'brand',
      atlaskit: 'primary',
    },
    secondary: {
      shadcn: 'secondary',
      mui: 'default',
      antd: 'default',
      chakra: 'purple',
      primer: 'secondary',
      polaris: 'new',
      carbon: 'cool-gray',
      fluent: 'tint',
      lightning: 'inverse',
      atlaskit: 'new',
    },
    outline: {
      shadcn: 'outline',
      mui: 'default',
      antd: 'default',
      chakra: 'gray',
      primer: 'default', // Primer badges don't have distinct outline variant usually, handled by components
      polaris: 'info',
      carbon: 'outline',
      fluent: 'outline',
      lightning: 'light',
      atlaskit: 'default',
    },
    destructive: {
      shadcn: 'destructive',
      mui: 'error',
      antd: 'error',
      chakra: 'red',
      primer: 'danger',
      polaris: 'critical',
      carbon: 'red',
      fluent: 'danger', // custom
      lightning: 'error',
      atlaskit: 'removed',
    },
    success: {
      shadcn: 'default', // shadcn default is often black/white
      mui: 'success',
      antd: 'success',
      chakra: 'green',
      primer: 'success',
      polaris: 'success',
      carbon: 'green',
      fluent: 'filled', // custom
      lightning: 'success',
      atlaskit: 'success',
    },
    warning: {
      shadcn: 'secondary',
      mui: 'warning',
      antd: 'warning',
      chakra: 'yellow',
      primer: 'attention',
      polaris: 'warning',
      carbon: 'magenta',
      fluent: 'filled', // custom
      lightning: 'warning',
      atlaskit: 'moved',
    },
    info: {
      shadcn: 'secondary',
      mui: 'info',
      antd: 'processing',
      chakra: 'blue',
      primer: 'accent',
      polaris: 'info',
      carbon: 'cyan',
      fluent: 'filled',
      lightning: 'inverse',
      atlaskit: 'primary',
    },
  },
  size: {
    small: {
      shadcn: 'sm',
      mui: 'small',
      antd: 'small',
      chakra: 'sm',
      primer: 'small',
      polaris: 'slim',
      carbon: 'sm',
      fluent: 'small',
      lightning: 'small',
      atlaskit: 'small',
    },
    medium: {
      shadcn: 'default',
      mui: 'medium',
      antd: 'middle',
      chakra: 'md',
      primer: 'medium',
      polaris: 'medium',
      carbon: 'md',
      fluent: 'medium',
      lightning: 'medium',
      atlaskit: 'medium',
    },
    large: {
      shadcn: 'lg',
      mui: 'large',
      antd: 'large',
      chakra: 'lg',
      primer: 'large',
      polaris: 'large',
      carbon: 'lg',
      fluent: 'large',
      lightning: 'large',
      atlaskit: 'large',
    },
  },
};
